# Exemplo de docker-compose.yml (ajuste conforme o seu)
version: '3.8'

services:
  n8n:
    image: n8n.io/n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/ # Este será sobrescrito pelo ngrok
      - GENERIC_TIMEZONE=America/Sao_Paulo
      # ... outras variáveis de ambiente do n8n

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command: "http n8n:5678" # Conecta ao serviço 'n8n' na porta 5678 dentro da rede Docker
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN} # Importante: você precisa definir NGROK_AUTHTOKEN no seu arquivo .env
    ports:
      - "4040:4040" # Opcional: expõe a UI do ngrok para inspeção em http://localhost:4040
    depends_on:
      - n8n # Garante que o n8n inicie antes do ngrok