// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://pppnieeztijtvwencdng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwcG5pZWV6dGlqdHZ3ZW5jZG5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MDc3NjAsImV4cCI6MjA3MzQ4Mzc2MH0.YewGT-qSBmfiCsKtbMBBrPXflE3Jgoi_xoyQ8BBmc64";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);